### ISSUE TITLE
Width detection issue in Chromium

### ISSUE THREAD

**Issue by doktorbro** [doktorbro/imadaem#2]
The window’s width is 1265 pixel. The image’s parent div’s width is set to

``` css
div { width: 33%}
img { width: 100%}
```

Chromium says the computed width of the image as 417.4375 pixel. It get streched to 418 pixel. But `clientWidth` is 417 and `offsetWidth` is 418.

How does it work?
